### ISSUE TITLE
TeX export has newlines

### ISSUE THREAD

**Issue by thirs** [amblafont/graph-editor-web#8]
It would be better if the TeX export could avoid having unnecessary new lines. E.g., if you have several diagrams in a row, this forces new lines in the final pdf. You can of course remove them manually, but could yade remove them in the first place?

**Comment by amblafont** [comment]
I am not sure what you mean, but since you implemented the TeX export, can you fix it?

**Comment by thirs** [comment]
Sorry, I should have said the problem is with the --watch feature, and I don't yet understand how this is done.
In particular, there is an empty line before % END GENERATED LATEX, which should be really easy for you to remove, right?
